services:
  - type: web
    name: pulsecare-api
    dir: server
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: DB_PATH
        value: /var/data/data.db
      - key: GEMINI_API_KEY
        scope: build
      - key: RECAPTCHA_SECRET
        scope: build
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
